// Build script: compiles the Peggy grammar into a standalone TypeScript parser.
// Run via: pnpm run build:grammar

import peggy from 'peggy';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const grammarPath = join(__dirname, '..', 'source', 'grammar', 'metrics-insights.pegjs');
const outputDir = join(__dirname, '..', 'source', 'generated');
const outputPath = join(outputDir, 'parser.js');

console.log(`Compiling grammar: ${grammarPath}`);

const grammarSource = readFileSync(grammarPath, 'utf-8');

try {
  const parserSource = peggy.generate(grammarSource, {
    output: 'source',
    format: 'es',
    allowedStartRules: ['Query', 'SelectClause', 'FromClause', 'WhereClause', 'GroupByClause', 'OrderByClause', 'LimitClause'],
    trace: false,
    cache: false,
  });

  mkdirSync(outputDir, { recursive: true });

  const header = [
    '// @generated — Do not edit directly.',
    '// Generated by scripts/build-grammar.ts',
    '//',
    '// This file contains the compiled Peggy parser for CloudWatch Metrics Insights queries.',
    '// The source grammar is at source/grammar/metrics-insights.pegjs',
    '',
    '// eslint-disable',
    '// @ts-nocheck',
    '',
  ].join('\n');

  writeFileSync(outputPath, header + parserSource, 'utf-8');
  console.log(`Parser written to: ${outputPath}`);
  console.log(`Size: ${(parserSource.length / 1024).toFixed(1)} KB`);

  // Also write a declaration file for the generated parser
  const declPath = join(outputDir, 'parser.d.ts');
  const declaration = [
    '// @generated — Do not edit directly.',
    '// Type declarations for the Peggy-generated parser.',
    '',
    'export interface PegSyntaxError extends Error {',
    "  expected: { type: string; description: string }[];",
    '  found: string | null;',
    '  location: {',
    '    start: { offset: number; line: number; column: number };',
    '    end: { offset: number; line: number; column: number };',
    '  };',
    '}',
    '',
    'export function parse<T = unknown>(input: string, options?: { startRule?: string }): T;',
    'export const StartRules: string[];',
    'export const SyntaxError: new (message: string, expected: unknown[], found: string | null, location: unknown) => PegSyntaxError;',
    '',
  ].join('\n');
  writeFileSync(declPath, declaration, 'utf-8');
  console.log(`Declarations written to: ${declPath}`);
} catch (err) {
  console.error('Grammar compilation failed:', err instanceof Error ? err.message : err);
  process.exit(1);
}
